# This is a basic workflow to help you get started with Actions

name: Stage the app

# Controls when the workflow will run
on:
  # Triggers the workflow on pull_request > labeled type
  pull_request:
    types: [ "labeled" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Check if the pull request type is 'stage'
    if: contains(github.event.pull_request.labels.*.name, 'stage')
